k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_gothic-context-296516_asia-southeast1-a_pack-n-go
  currentCluster: gke_gothic-context-296516_asia-southeast1-a_pack-n-go
  clusters:
    gke_gothic-context-296516_asia-southeast1-a_pack-n-go:
      namespace:
        active: ""
        favorites:
        - all
        - default
        - gitlab-managed-apps
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
