alias npmd="npm run dev"
alias npms="npm start"
alias npmi="npm install"
alias npmig="npm install -g"
alias npmid="npm install --save-dev"
alias npmiy="npm init -y"
alias npmu="npm uninstall"
alias npmb="npm run build"
alias npmr="npm run"

alias yi="yarn install"
alias ya="yarn add"
alias yga="yarn global add"
alias ys="yarn start"
alias yd="yarn dev"
alias yb="yarn build"
alias ybw="yarn build-watch"
